#ifndef ENSICOIN_UTILS_AUTOMATA_ADDRESS_H
#define ENSICOIN_UTILS_AUTOMATA_ADDRESS_H

#include <stdint.h>

struct ensicoin_automata_address {
	enum ensicoin_automata_address_state {
		ENSICOIN_AUTOMATA_ADDRESS_TIMESTAMP_1_LEFT,
		ENSICOIN_AUTOMATA_ADDRESS_TIMESTAMP_2_LEFT,
		ENSICOIN_AUTOMATA_ADDRESS_TIMESTAMP_3_LEFT,
		ENSICOIN_AUTOMATA_ADDRESS_TIMESTAMP_4_LEFT,
		ENSICOIN_AUTOMATA_ADDRESS_TIMESTAMP_5_LEFT,
		ENSICOIN_AUTOMATA_ADDRESS_TIMESTAMP_6_LEFT,
		ENSICOIN_AUTOMATA_ADDRESS_TIMESTAMP_7_LEFT,
		ENSICOIN_AUTOMATA_ADDRESS_TIMESTAMP_8_LEFT,
		ENSICOIN_AUTOMATA_ADDRESS_TIMESTAMP_END,
		ENSICOIN_AUTOMATA_ADDRESS_IP_1_LEFT,
		ENSICOIN_AUTOMATA_ADDRESS_IP_2_LEFT,
		ENSICOIN_AUTOMATA_ADDRESS_IP_3_LEFT,
		ENSICOIN_AUTOMATA_ADDRESS_IP_4_LEFT,
		ENSICOIN_AUTOMATA_ADDRESS_IP_5_LEFT,
		ENSICOIN_AUTOMATA_ADDRESS_IP_6_LEFT,
		ENSICOIN_AUTOMATA_ADDRESS_IP_7_LEFT,
		ENSICOIN_AUTOMATA_ADDRESS_IP_8_LEFT,
		ENSICOIN_AUTOMATA_ADDRESS_IP_9_LEFT,
		ENSICOIN_AUTOMATA_ADDRESS_IP_10_LEFT,
		ENSICOIN_AUTOMATA_ADDRESS_IP_11_LEFT,
		ENSICOIN_AUTOMATA_ADDRESS_IP_12_LEFT,
		ENSICOIN_AUTOMATA_ADDRESS_IP_13_LEFT,
		ENSICOIN_AUTOMATA_ADDRESS_IP_14_LEFT,
		ENSICOIN_AUTOMATA_ADDRESS_IP_15_LEFT,
		ENSICOIN_AUTOMATA_ADDRESS_IP_16_LEFT,
		ENSICOIN_AUTOMATA_ADDRESS_IP_END,
		ENSICOIN_AUTOMATA_ADDRESS_PORT_1_LEFT,
		ENSICOIN_AUTOMATA_ADDRESS_PORT_2_LEFT,
		ENSICOIN_AUTOMATA_ADDRESS_PORT_END,
		ENSICOIN_AUTOMATA_ADDRESS_DISCARDING
	} state;

	union {
		uint64_t timestamp;
		uint8_t ip[16];
		uint16_t port;
	};
};

void
ensicoin_automata_address_start(struct ensicoin_automata_address *automata);

enum ensicoin_automata_address_state
ensicoin_automata_address_update(struct ensicoin_automata_address *automata,
	uint8_t byte);

/* ENSICOIN_UTILS_AUTOMATA_ADDRESS_H */
#endif
